### ISSUE TITLE
investigate into docker push --all-tags

### ISSUE THREAD

**Issue by dogi** [treehouses/alpine#40]
https://github.com/treehouses/alpine/commit/6d3d7412c015f5cba8d9b4dbd27670b38bb1f084

**Comment by rjpadilla** [comment]
Its possible that `tag can't be used with --all-tags/-a` in https://github.com/treehouses/alpine/runs/3307881372?check_suite_focus=true#step:4:35 is referring to how the `$repo` variable should not contain any tags. See https://github.com/treehouses/alpine/blob/6d3d7412c015f5cba8d9b4dbd27670b38bb1f084/.github/workflows/alpine.yml#L76 
The `$repo` variable should not have `:<name of tag>` after its name when pushing.
